#overcooked env
env: "overcooked"

env_args:
    map_name: "A"


test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
